name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: | 
          echo "Hello World!"
          echo "If you can read this text..."
          echo "...you are the resistance..."
      - name: Print goodbye
        run: echo "Mmmkay - bye!"
